name: Contray-System
version: 1.0.0
author: Fabtopf

main: de.Fabtopf.System.Utilities.Main

soft-depends: [PermissionsEx]

commands:
  ban:
    description: Command to ban a Player
    usage: /<command> <Player> <Reason>
    permission: contray.system.banmodule.ban
    aliases: [cban]
  unban:
    description: Command to unban a Player
    usage: /<command> <Player>
    permission: contray.system.banmodule.unban
    aliases: [cunban]
  tempban:
    description: Command to tempban a Player
    usage: /<command> <Player> <Timestamp> <Reason>
    permission: contray.system.banmodule.tempban
    aliases: [ctempban]
  mute:
    description: Command to mute a Player
    usage: /<command> <Player> <Reason>
    permission: contray.system.mutemodule.mute
    aliases: [cmute]
  unmute:
    description: Command to unmute a Player
    usage: /<command> <Player>
    permission: contray.system.mutemodule.unmute
    aliases: [cunmute]
  tempmute:
    description: Command to tempmute a Player
    usage: /<command> <Player> <Timestamp> <Reason>
    permission: contray.system.mutemodule.tempmute
    aliases: [ctempmute]
  blockcommand:
    description: Command to block other commands
    usage: /<command> list | add <Command> [check_contain] [exempt_Permission] | remove <Command>
    permission: contray.system.blockcommandmodule.blockcommand
    aliases: [cblockcommand, blockcmd, cblockcmd]
  freeze:
    description: Command to toggle freeze-state of a player
    usage: /<command> <Player> [on|off]
    permission: contray.system.freezemodule.freeze
    aliases: [cfreeze]


permissions:
  contray.system.*:
    description: Allows to use all Contray-System features
    default: op
    children:
      - contray.system.banmodule.*: true
      - contray.system.banmodule.ban: true
      - contray.system.banmodule.unban: true
      - contray.system.banmodule.tempban: true
      - contray.system.banmodule.exempt: true
      - contray.system.mutemodule.*: true
      - contray.system.mutemodule.mute: true
      - contray.system.mutemodule.unmute: true
      - contray.system.mutemodule.tempmute: true
      - contray.system.mutemodule.exempt: true
      - contray.system.blockcommandmodule.*: true
      - contray.system.blockcommandmodule.blockcommand: true
      - contray.system.blockcommandmodule.exempt: true
      - contray.system.freezemodule.*: true
      - contray.system.freezemodule.freeze: true
      - contray.system.freezemodule.carry: true
      - contray.system.freezemodule.exempt: true
  contray.system.banmodule.*:
    description: Allows tu use all Ban-Module features
    default: op
    children:
      - contray.system.banmodule.ban: true
      - contray.system.banmodule.unban: true
      - contray.system.banmodule.tempban: true
      - contray.system.banmodule.exempt: true
  contray.system.mutemodule.*:
    description: Allows to use all Mute-Module features
    default: op
    children:
      - contray.system.mutemodule.mute: true
      - contray.system.mutemodule.unmute: true
      - contray.system.mutemodule.tempmute: true
      - contray.system.mutemodule.exempt: true
  contray.system.blockcommand.*:
    description: Allows to use all BlockCommand-Module features
    default: op
    children:
      - contray.system.blockcommandmodule.blockcommand: true
      - contray.system.blockcommandmodule.exempt: true
  contray.system.freezemodule.*:
    description: Allows tu use all Freeze-Module features
    default: op
    children:
      - contray.system.freezemodule.freeze: true
      - contray.system.freezemodule.carry: true
      - contray.system.freezemodule.exempt: true

